appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: ZU0DHs//AMWLK9aC+T1hNzwTupcSXbxgkKxu0Sa6ABaOrLZ58/JV5EylHD5Bs0qUAgzGgpkfcdB/y5V9NOUkldhD/gU3vMuOSnXWJNnAEmOf/Iz2zIbFQu0rxRt/ftBYdnO3TAgr9QjrBDDBKlmcIrGARWdf3jGA3TPt0+Pc6IRv5cW4N5SHJgOittSdGHzU3PhcU7JHtMmsRMdwZoxQ3E6mDAm88//A44W0AUVXiDQVKYqTYwCjZAIWruKTsGpejCF1Xuqe4LfFkXw1fd+Nzd4rxrk8aDOFI22eZj3nsJgaWYlqDC3EtvnB9EHdYypswYUXh8Il0+2xeI665bD+qz59iF802q+mf8vRGDE13Op2qVKJTTXp+6JPu42npXw8uCW3Qv3qinNAQnjEjyaaS3y0Kgo04hcC7fJ9dTdHRSHeei+ue0WqKqI/XQ6NM65cgWiTK/3xO+zQXYtVfvp4CSutW8yNR1c5dtJSXZocTAEC3gqA7oHQu8FODcqskCx1H4GcqkePln15j7Ht5yqe26mFJn7bWFJrazxW6zJASAu4/hksb234QH9mXVFz42MIHp1k12TBQPtAmD5Mqa06D3KPLomPu3OGK99ZE9d6oJNOhf/3iXFziE9V0adfU/DoqVU1W8YewwWx1d/7QPi19e8ebTjRfQxIld8XDIYEx3k=}
bot:
  automerge: true
